const sampleData = {
  products: [
    {
      name: 'JJK Bean Charms',
      slug: 'jjk-bean-charms',
      category: 'Charms',
      description:
        'Adorable chibi-style bean charms featuring your favorite Jujutsu Kaisen characters. Perfect for keychains, bags, or collecting!',
      images: [
        '/images/products/charms/Bean Charms/all.webp',
        '/images/products/charms/Bean Charms/gojo-front.webp',
        '/images/products/charms/Bean Charms/trio.webp',
        '/images/products/charms/Bean Charms/choso.webp',
        '/images/products/charms/Bean Charms/CSMtrio.webp',
        '/images/products/charms/Bean Charms/gojo-back.avif',
        '/images/products/charms/Bean Charms/killua.webp',
        '/images/products/charms/Bean Charms/nanami.avif',
        '/images/products/charms/Bean Charms/satosagu.avif',
      ],
      price: 12.99,
      brand: 'MilkkoStore',
      rating: 4.8,
      numReviews: 24,
      stock: 15,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'VALORANT Girls Charms',
      slug: 'valorant-girls-charms',
      category: 'Charms',
      description:
        'Show your agent loyalty with these stylish VALORANT female agent charms. Features Jett, Sage, Reyna, and more!',
      images: [
        '/images/products/charms/VALORANT girls/all.webp',
        '/images/products/charms/VALORANT girls/all-2.webp',
        '/images/products/charms/VALORANT girls/jett.webp',
        '/images/products/charms/VALORANT girls/sage.webp',
        '/images/products/charms/VALORANT girls/killjoy.jpg',
        '/images/products/charms/VALORANT girls/neon.webp',
        '/images/products/charms/VALORANT girls/raze.webp',
        '/images/products/charms/VALORANT girls/reyna.jpg',
      ],
      price: 14.99,
      brand: 'MilkkoStore',
      rating: 4.6,
      numReviews: 18,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'JJK Itafushi Photocards',
      slug: 'jjk-itafushi-photocards',
      category: 'Photocards',
      description:
        'Beautiful high-quality photocards featuring Itadori and Fushiguro. Double-sided design with premium finish.',
      images: [
        '/images/products/photocards/JJK/itafushi.webp',
        '/images/products/photocards/JJK/itafuchi-back.webp',
      ],
      price: 8.99,
      brand: 'MilkkoStore',
      rating: 4.9,
      numReviews: 32,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'SatoSugu Cute Photocards',
      slug: 'satosugu-cute-photocards',
      category: 'Photocards',
      description:
        'Heartwarming photocards of Gojo and Geto in their school days. Perfect for any JJK fan!',
      images: [
        '/images/products/photocards/JJK/satosagu-cute.webp',
        '/images/products/photocards/JJK/satosagu-cute-back.webp',
      ],
      price: 8.99,
      brand: 'MilkkoStore',
      rating: 4.7,
      numReviews: 28,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'SatoSugu Fish Photocards',
      slug: 'satosugu-fish-photocards',
      category: 'Photocards',
      description:
        'Unique artistic photocards featuring Gojo and Geto with beautiful fish-themed artwork.',
      images: [
        '/images/products/photocards/JJK/satosagu-fish.webp',
        '/images/products/photocards/JJK/satosagu-fish-back.webp',
      ],
      price: 9.99,
      brand: 'MilkkoStore',
      rating: 4.8,
      numReviews: 15,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Strawhat Pirates Sticker Pack',
      slug: 'strawhat-pirates-sticker-pack',
      category: 'Stickers',
      description:
        'Set sail with the Strawhat crew! High-quality vinyl stickers perfect for laptops, water bottles, and more.',
      images: [
        '/images/products/stickers/Strawhat/strawhat-1.webp',
        '/images/products/stickers/Strawhat/strawhat-2.webp',
        '/images/products/stickers/Strawhat/strawhat-3.webp',
        '/images/products/stickers/Strawhat/strawhat-4.webp',
      ],
      price: 6.99,
      brand: 'MilkkoStore',
      rating: 4.5,
      numReviews: 42,
      stock: 30,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'VALORANT Agents Sticker Pack',
      slug: 'valorant-agents-sticker-pack',
      category: 'Stickers',
      description:
        'Rep your favorite agents with this comprehensive VALORANT sticker collection. Waterproof and fade-resistant.',
      images: [
        '/images/products/stickers/VALORANT agents/valorant-1.webp',
        '/images/products/stickers/VALORANT agents/valorant-2.webp',
        '/images/products/stickers/VALORANT agents/valorant-3.webp',
        '/images/products/stickers/VALORANT agents/valorant-4.webp',
        '/images/products/stickers/VALORANT agents/valorant-5.webp',
        '/images/products/stickers/VALORANT agents/valorant-6.jpg',
        '/images/products/stickers/VALORANT agents/valorant-7.jpg',
      ],
      price: 7.99,
      brand: 'MilkkoStore',
      rating: 4.6,
      numReviews: 35,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
